module.exports = {
	NEW_REQUEST_RECEIVED: "NEW_REQUEST_RECEIVED",
	USER_REQUEST_RECEIVED: "USER_REQUEST_RECEIVED",
	REQUESTS_RECEIVED: "REQUESTS_RECEIVED",
	REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
	REQUEST_REJECTED: "REQUEST_REJECTED"
};
